apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  #labels for development resources
  labels:
    app: mysql
    tier: mysql
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: mysql
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
        project: expense
    spec:
      containers:
      - name: mysql
        image: devsecopswithaws/mysql:1.0.0